config/routes.rb
Rails.application.routes.draw do

  # Add a new restaurant
  resources :restaurants do
    #resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5]}
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show

  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="col-xs-12 col-md-12">
    <div class="row">
      <h1>🤘 Yelp</h1>
      <p>Find the perfect restaurant for lunch</p>
      <div class="box">
        <% @restaurants.each do |restaurant| %>
          <h2>🍜 <%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
        <% end %>
      </div>
      <%= link_to "add a restaurant", new_restaurant_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="col-xs-12 col-md-4">
    <div class="row">
      <h1>🍽 Add an tasty restaurant</h1>
      <%= simple_form_for [@restaurant] do |f| %>
        <!-- All info necessary for creating a restaurants -->
        <%= f.input :name %>
        <%= f.input :category, collection: %w(chinese italian japanese french belgian) %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.submit "Add a restaurant", class: "btn btn-primary"%>
      <% end %>
      <%= link_to "List others restaurants", "/restaurants", class: "btn btn-secondary btn-sm" %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="col-xs-12 col-md-4">
    <div class="row">
      <h1><%= @restaurant.name %></h1>
      <h2><%= @restaurant.category.capitalize %></h2>
      <p>📍 <%= @restaurant.address %></p>
      <p>🎙 <%= @restaurant.phone_number %></p>
    </div>
      <div class = "btn btn-light-dark">
        <%= link_to "Back to restaurants", "/restaurants" %>
      </div>
    </div>
  </div>
</div>